### ISSUE TITLE
Custom npm registry server not working with Yarn 2+

### ISSUE THREAD

**Issue by srmagura** [raineorshine/npm-check-updates#1109]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 12`

---------------------------

## Steps to Reproduce

1. Use Yarn 3: `yarn set version berry`
2. Configure FontAwesome custom registry in `.yarnrc.yml` like this:

    ```yaml
    npmScopes:
      fortawesome:
        npmAlwaysAuth: true
        npmAuthToken: YOUR-AUTH-TOKEN
        npmRegistryServer: "https://npm.fontawesome.com/"
    ```

3. Add a FontAwesome Pro dependency: `yarn add @fortawesome/pro-duotone-svg-icons`
4. Run `npm-check-updates`

## Current Behavior

```text
FetchError: Request @fortawesome/pro-duotone-svg-icons info failed[3 of 3]: 
Unable to authenticate, need: Basic realm="https://npm.fontawesome.com/",service="npm.fontawesome.com".
```

## Expected Behavior

npm-check-updates gets the auth token from `.yarnrc.yml` so that the requests succeed.

I may try to submit a PR for this. Let me know if you have any implementation guidance.
