### ISSUE TITLE
No support for environment variables from yarnrc.yml

### ISSUE THREAD

**Issue by kamronbatman** [raineorshine/npm-check-updates#1216]
- [X] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [X] I am using the latest version of `npm-check-updates`
- [X] I am using `node >= 14.14`

---

## Steps to Reproduce

Add a custom npmRegistryServer, like this:

```yml
npmScopes:
  mycompanynamespace:
    npmRegistryServer: "${MY_COMPANY_NPM_REGISTRY-https://artifactory.internal/artifactory/npm/npm-all}"
```

Steps:

Run `ncu` with, and without the environment variable set.

## Current Behavior

ncu throws an error because it can't determine the server.

## Expected Behavior

ncu should parse properly and use that registry server.
