### ISSUE TITLE
Only the first workspace package is checked

### ISSUE THREAD

**Issue by alexgorbatchev** [raineorshine/npm-check-updates#1416]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)

---

## Steps to Reproduce

.ncurc:

```yaml
interactive: true
upgrade: true
workspaces: true
format: [group, repo]
target: latest
packageManager: yarn
install: never
loglevel: info
```

workspace `package.json`:

```json
{
  "name": "foo",
  "version": "1.0.2",
  "private": true,
  "license": "UNLICENCED",
  "workspaces": {
    "packages": ["a/*", "b/*", "c/*", "d/*"]
  },
```

Steps:

## Current Behavior

```
❯ ncu
Using config file /Users/proj/.ncurc.yml
Upgrading /Users/proj/a/pkg1/package.json
[====================] 11/11 100%

All dependencies match the latest package versions :)
Upgrading /Users/proj/a/pkg2/package.json
[====================] 24/24 100%

? Choose which packages to update › 
  ↑/↓: Select a package
  Space: Toggle selection
  a: Toggle all
  Enter: Upgrade 

...
```

For some reason only the first value from `workspace.packages` is traversed. Furthermore, I only see first two packages under `a` checked, eg `pkg1` and `pkg2`, however there are over 10. None of the other `workspace.packages` are checked.

## Expected Behavior

All `workspace.packages` should be checked.
